<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vm</string>
		<string>xml</string>
	</array>
	<key>firstLineMatch</key>
	<string>&lt;scriptedContentFragments&gt;</string>
	<key>foldingStartMarker</key>
	<string>#(if(\((.*)\)))|foreach|elseif)</string>
	<key>foldingStopMarker</key>
	<string>#end</string>
	<key>name</key>
	<string>Velocity Widgets</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;!\[CDATA\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-dash.vm</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;![CDATA[]] block</string>
			<key>end</key>
			<string>(\]\]&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-dash.vm</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single line comment</string>
			<key>match</key>
			<string>(##).*$
?</string>
			<key>name</key>
			<string>comment.line.double-pound.vm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")|(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.vm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.vm</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.double.vm</string>
			<key>end</key>
			<string>(")|(')</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.vm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.vm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Flow controls</string>
			<key>match</key>
			<string>(#if|#elseif|#else|#end|#foreach|#beforeall|#each|#afterall|#nodata|#set|#registerEndOfPageHtml)</string>
			<key>name</key>
			<string>storage.type.var.vm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|==|!=|&amp;|&amp;&amp;|\|\||\||&gt;=|&gt;</string>
			<key>name</key>
			<string>keyword.operator.vm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(true|false)</string>
			<key>name</key>
			<string>constant.language.vm</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#vmproperty</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#vmvariable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>vmproperty</key>
		<dict>
			<key>begin</key>
			<string>(\$!?\{?[a-zA-Z][a-zA-Z0-9-_]*)(\.[a-zA-Z][a-zA-Z\.0-9-_]*)+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.vm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.vm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\((.*[^\)])?\))?(\})?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text.velocity</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.vm</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>vmvariable</key>
		<dict>
			<key>match</key>
			<string>\$!?(\{([a-zA-Z][a-zA-Z0-9-_]*)\}|[a-zA-Z][a-zA-Z0-9-_]*)</string>
			<key>name</key>
			<string>variable.language.vm</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.velocity</string>
	<key>uuid</key>
	<string>9288bbc3-6728-48e6-8fe1-cf19ddad8f7c</string>
</dict>
</plist>
